demo/demo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('myweb/', include('myweb.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

demo/myweb/urls.py
from django.urls import path
from . import views

# urlpatterns = [
#     path('', views.index, name='index'),
# ]

app_name = 'myweb'

# urlpatterns = [
#     # ex: /myweb/
#     path('', views.index, name='index'),
#     # ex: /myweb/5/
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /myweb/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /myweb/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

demo/myweb/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # was_published_recently.admin_order_field = 'pub_date'
    # was_published_recently.boolean = True
    # was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

demo/myweb/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.template import loader

from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.urls import reverse
from django.views import generic
from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'myweb/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'myweb/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'myweb/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('myweb/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'myweb/index.html', context)


# def index(request):     # request是必须带的实例。类似class下方法必须带self一样
#     return HttpResponse("Hello World!!")    # 通过HttpResponse模块直接返回字符串到前端页面


# # 先定义一个数据列表，当然后面熟了可以从数据库里取出来
# list = [{"name": 'lili', 'password': '0919'}, {'name': 'huahua', 'password': 'youguess'}]
#
#
# def index(request):
#     # 获取前端post过来的用户名和密码
#     name = request.POST.get("name", None)
#     password = request.POST.get("password", None)
#
#     # 把用户和密码组装成字典
#     data = {"name": name, "password": password}
#     list.append(data)
#
#     return render(request, 'index.html', {'form': list})


# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'myweb/detail.html', {'question': question})

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'myweb/detail.html', {'question': question})


# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'myweb/results.html', {'question': question})


# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'myweb/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('myweb:results', args=(question.id,)))

demo/myweb/templates/myweb/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'myweb:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

demo/myweb/templates/myweb/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
 <form action="index.html" method="post">
<!action文本内容写到index.html中,与path的index.html相呼应!>
        {% csrf_token %}
        <p>
            <label>用户名：</label>
            <!下拉框部分!>
            <input type="text" list="aa" name="name"/>
            <datalist id = "aa">
                <option value="chanyeol" />
                <option value="beakhyun" />
                <option value="sehun" />
            </datalist>
        </p>
        <p>
            <lable>密码：</lable>
            <input type="text" list="bb" name="password"/>
             <datalist id = "bb">
                <option value="20001127sn" label="SN"/>
                <option value="19980506bk" label="BK"/>
                <option value="5bzsdixh99" label="SN"/>
            </datalist>
        </p>
        <p>
            <input type="submit" value="提交"/>
        </p>
    </form>
<table border="6", bgcolor="green">

    <thead> <!html中的表头内容!>
    <tr>
        <td>用户名</td>
        <td>密码</td>
    </tr>
    </thead>
    {% for line in form %}
        <tr>
            <td>{{line.name}}</td>
            <td>{{line.password}}</td>
        </tr>
    {% endfor %}

</table>

 <br>
 <img src="/static/myweb/images/test.png"/>

</body>
</html>

demo/myweb/templates/myweb/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'myweb/css/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'myweb:detail' question.id %}">{{ question.question_text }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

demo/myweb/templates/myweb/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'myweb:detail' question.id %}">Vote again?</a>